<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>..\EShop.Web\Modules\EShop.OfflinePayment</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>
    

    <ItemGroup>
        <ProjectReference Include="..\EShop.Core\EShop.Core.csproj"/>
        <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj"/>
        <ProjectReference Include="..\EShop.Web.Framework\EShop.Web.Framework.csproj"/>
    </ItemGroup>

</Project>
