// <auto-generated />
using System;
using EShop.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EShop.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715111844_10")]
    partial class _10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Discount_CategoryDiscount_Mapping", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Discount_CategoryDiscount_Mapping");
                });

            modelBuilder.Entity("Discount_ProductDiscount_Mapping", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("DiscountId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Discount_ProductDiscount_Mapping");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TextPrompt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalog_ProductAttribute", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductAttributeOptionsSetId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightAdjustment")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeOptionsSetId");

                    b.ToTable("Catalog_ProductAttributeOption", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOptionsSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.ToTable("Catalog_ProductAttributeOptionsSet", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductSpecificationAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecificationAttributeOptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SpecificationAttributeOptionId");

                    b.ToTable("Catalog_ProductSpecificationAttribute", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeControlTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Catalog_ProductAttribute_Mapping", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttributeCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePriceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BasePriceBaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("DeliveryTimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Gtin")
                        .HasColumnType("text");

                    b.Property<int>("HashCode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Length")
                        .HasColumnType("numeric");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantityUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("RawAttributes")
                        .HasColumnType("jsonb");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTimeId");

                    b.HasIndex("ProductId");

                    b.ToTable("Catalog_ProductVariantAttributeCombination", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEssential")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductVariantAttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightAdjustment")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantAttributeId");

                    b.ToTable("Catalog_ProductVariantAttributeValue", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.SpecificationAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<bool>("AllowFiltering")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalog_SpecificationAttribute", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.SpecificationAttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumberValue")
                        .HasColumnType("integer");

                    b.Property<int>("SpecificationAttributeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationAttributeId");

                    b.ToTable("Catalog_SpecificationAttributeOption", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Brands.Domain.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.ToTable("Catalog_Brand", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Categories.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDiscountsApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeInMenu")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRootParent")
                        .HasColumnType("boolean");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("ParentId");

                    b.ToTable("Catalog_Category", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Categories.Domain.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Catalog_ProductCategory", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedRatingSum")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovedReviewCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AttributeCombinationRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BasePriceAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BasePriceBaseAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CombinationDisplayBehaviour")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("DeliveryTimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool>("DisplayStockQuantity")
                        .HasColumnType("boolean");

                    b.Property<string>("Gtin")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("HasDiscountsApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasOptions")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("HomePageDisplayOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShippingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleIndividually")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Length")
                        .HasColumnType("numeric");

                    b.Property<int?>("MaxAddToCartNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NotApprovedRatingSum")
                        .HasColumnType("integer");

                    b.Property<int>("NotApprovedReviewCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantityUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("boolean");

                    b.Property<string>("Sku")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Catalog_Product", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.ProductLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("LinkedProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LinkedProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Catalog_ProductLink", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Catalog_ProductReview", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplierName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReplyStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReplyText")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("Catalog_Reply", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Price.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CouponUsageAmount")
                        .HasColumnType("integer");

                    b.Property<int>("CouponUsageType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountUsageAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndsOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCouponRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartsOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsePercentage")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("Catalog_Discount", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Price.DiscountBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Catalog_DiscountBadge", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Price.DiscountUsageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrderId");

                    b.ToTable("Catalog_DiscountUsageHistory", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Checkout.Order.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Checkout_Order", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Common_Address", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCityEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShippingEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsZipCodeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Common_City", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.DeliveryTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHexValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayLocate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Common_DeliveryTime", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Common_Label", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.ProductLabel", b =>
                {
                    b.Property<int>("LabelId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("LabelId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Common_ProductLabel", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Common_UserAddress", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Content.Media.Domain.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Content_MediaFile", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Content.Media.Domain.ProductMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("ProductId");

                    b.ToTable("Content_ProductMedia", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Content.Widgets.Domain.Widget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CreateUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditUrl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ViewComponentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Content_Widget", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Content.Widgets.Domain.WidgetInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("smallint");

                    b.Property<string>("HtmlData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LatestUpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PublishEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WidgetId")
                        .HasColumnType("text");

                    b.Property<int>("WidgetZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WidgetId");

                    b.HasIndex("WidgetZoneId");

                    b.ToTable("Content_WidgetInstance", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Content.Widgets.Domain.WidgetZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Content_WidgetZone", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Data.Cart.Domain.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RawAttributes")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Data_ShoppingCartItem", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Configuration.Domain.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platform_Setting", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.ExternalIdentityLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platform_ExternalIdentityLogin", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platform_Role", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClientIdentity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscountCouponCode")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExtensionData")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastUserAgent")
                        .HasColumnType("text");

                    b.Property<string>("LastUserDeviceType")
                        .HasColumnType("text");

                    b.Property<string>("LastVisitedPage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LatestUpdateOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemName")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Platform_User", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Platform_UserRole", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Logging.Domain.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityLogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Platform_ActivityLog", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Logging.Domain.ActivityLogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SystemKeyword")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platform_ActivityLogType", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Routing.Domain.EntityType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TargetActionName")
                        .HasColumnType("text");

                    b.Property<string>("TargetAreaName")
                        .HasColumnType("text");

                    b.Property<string>("TargetControllerName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platform_EntityType", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Routing.Domain.UrlRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platform_UrlRecord", (string)null);
                });

            modelBuilder.Entity("EShop.Core.Platform.Themes.Domain.ThemeVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Theme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Platform_ThemeVariable", (string)null);
                });

            modelBuilder.Entity("Discount_CategoryDiscount_Mapping", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Categories.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Price.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Discount_ProductDiscount_Mapping", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Price.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOption", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOptionsSet", "ProductAttributeOptionsSet")
                        .WithMany("ProductAttributeOptions")
                        .HasForeignKey("ProductAttributeOptionsSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductAttributeOptionsSet");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOptionsSet", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductAttributeOptionsSets")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductSpecificationAttribute", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductSpecificationAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.SpecificationAttributeOption", "SpecificationAttributeOption")
                        .WithMany("ProductSpecificationAttributes")
                        .HasForeignKey("SpecificationAttributeOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SpecificationAttributeOption");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttribute", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.ProductAttribute", "ProductAttribute")
                        .WithMany()
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductVariantAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttributeCombination", b =>
                {
                    b.HasOne("EShop.Core.Common.Domain.DeliveryTime", "DeliveryTime")
                        .WithMany()
                        .HasForeignKey("DeliveryTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductVariantAttributeCombinations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryTime");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttributeValue", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttribute", "ProductVariantAttribute")
                        .WithMany("ProductVariantAttributeValues")
                        .HasForeignKey("ProductVariantAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariantAttribute");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.SpecificationAttributeOption", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Attributes.Domain.SpecificationAttribute", "SpecificationAttribute")
                        .WithMany("SpecificationAttributeOptions")
                        .HasForeignKey("SpecificationAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpecificationAttribute");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Brands.Domain.Brand", b =>
                {
                    b.HasOne("EShop.Core.Content.Media.Domain.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Categories.Domain.Category", b =>
                {
                    b.HasOne("EShop.Core.Content.Media.Domain.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EShop.Core.Catalog.Categories.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MediaFile");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Categories.Domain.ProductCategory", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Categories.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.Product", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Brands.Domain.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.ProductLink", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "LinkedProduct")
                        .WithMany()
                        .HasForeignKey("LinkedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.ProductReview", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.Reply", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Domain.ProductReview", "ProductReview")
                        .WithMany("Replies")
                        .HasForeignKey("ProductReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductReview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Price.Discount", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Price.DiscountBadge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Price.DiscountUsageHistory", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Price.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Checkout.Order.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EShop.Core.Checkout.Order.Domain.Order", b =>
                {
                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.Address", b =>
                {
                    b.HasOne("EShop.Core.Common.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.ProductLabel", b =>
                {
                    b.HasOne("EShop.Core.Common.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Common.Domain.UserAddress", b =>
                {
                    b.HasOne("EShop.Core.Common.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Content.Media.Domain.ProductMedia", b =>
                {
                    b.HasOne("EShop.Core.Content.Media.Domain.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Content.Widgets.Domain.WidgetInstance", b =>
                {
                    b.HasOne("EShop.Core.Content.Widgets.Domain.Widget", "Widget")
                        .WithMany()
                        .HasForeignKey("WidgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EShop.Core.Content.Widgets.Domain.WidgetZone", "WidgetZone")
                        .WithMany()
                        .HasForeignKey("WidgetZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Widget");

                    b.Navigation("WidgetZone");
                });

            modelBuilder.Entity("EShop.Core.Data.Cart.Domain.ShoppingCartItem", b =>
                {
                    b.HasOne("EShop.Core.Catalog.Products.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", null)
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.User", b =>
                {
                    b.HasOne("EShop.Core.Common.Domain.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EShop.Core.Common.Domain.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.UserRole", b =>
                {
                    b.HasOne("EShop.Core.Platform.Identity.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EShop.Core.Platform.Identity.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttribute", b =>
                {
                    b.Navigation("ProductAttributeOptionsSets");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductAttributeOptionsSet", b =>
                {
                    b.Navigation("ProductAttributeOptions");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.ProductVariantAttribute", b =>
                {
                    b.Navigation("ProductVariantAttributeValues");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.SpecificationAttribute", b =>
                {
                    b.Navigation("SpecificationAttributeOptions");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Attributes.Domain.SpecificationAttributeOption", b =>
                {
                    b.Navigation("ProductSpecificationAttributes");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Brands.Domain.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Categories.Domain.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.Product", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductLinks");

                    b.Navigation("ProductReviews");

                    b.Navigation("ProductSpecificationAttributes");

                    b.Navigation("ProductVariantAttributeCombinations");

                    b.Navigation("ProductVariantAttributes");
                });

            modelBuilder.Entity("EShop.Core.Catalog.Products.Domain.ProductReview", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Core.Platform.Identity.Domain.User", b =>
                {
                    b.Navigation("ShoppingCartItems");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
