<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>..\EShop.Web\Modules\EShop.ExternalAuth.Google</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.9"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.2" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\EShop.Core\EShop.Core.csproj"/>
        <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj"/>
        <ProjectReference Include="..\EShop.Web.Framework\EShop.Web.Framework.csproj"/>
    </ItemGroup>

</Project>
