<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4ff4e5c3-3891-4461-a13a-95c915b2c4dc</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <PreserveCompilationReferences>false</PreserveCompilationReferences>
  </PropertyGroup>
  <PropertyGroup>
    <PreserveCompilationContext>false</PreserveCompilationContext>
  </PropertyGroup>
  
    <ItemGroup>
        <Folder Include="App_Data\" />
        <Folder Include="Themes\EShopDefault\wwwroot\" />
        <Folder Include="Views\Home\Partials\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EShop.Core\EShop.Core.csproj" />
        <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
        <ProjectReference Include="..\EShop.AzureBlobStorage\EShop.AzureBlobStorage.csproj" />
        <ProjectReference Include="..\EShop.ExternalAuth.Google\EShop.ExternalAuth.Google.csproj" />
     

    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="9.0.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Bogus" Version="35.6.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.15" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-grid.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-reboot.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap-utilities.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\css\bootstrap.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\js\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\bootstrap-grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\bootstrap-reboot.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\bootstrap-utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\bootstrap.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_floating-labels.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_form-check.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_form-control.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_form-range.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_form-select.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_form-text.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_input-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_labels.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\forms\_validation.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_clearfix.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_color-bg.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_colored-links.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_focus-ring.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_icon-link.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_position.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_ratio.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_stacks.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_stretched-link.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_text-truncation.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_visually-hidden.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\helpers\_vr.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_alert.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_backdrop.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_banner.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_border-radius.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_box-shadow.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_breakpoints.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_buttons.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_caret.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_clearfix.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_color-mode.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_color-scheme.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_container.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_deprecate.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_forms.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_gradients.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_image.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_list-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_lists.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_pagination.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_reset-text.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_resize.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_table-variants.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_text-truncate.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_transition.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\mixins\_visually-hidden.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\utilities\_api.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\vendor\_rfs.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_accordion.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_alert.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_badge.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_breadcrumb.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_button-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_buttons.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_card.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_carousel.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_close.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_containers.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_dropdown.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_forms.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_functions.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_grid.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_helpers.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_images.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_list-group.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_maps.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_mixins.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_modal.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_nav.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_navbar.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_offcanvas.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_pagination.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_placeholders.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_popover.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_progress.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_reboot.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_root.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_spinners.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_tables.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_toasts.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_tooltip.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_transitions.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_type.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_variables-dark.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\scss\_variables.scss" />
      <_ContentIncludedByDefault Remove="Themes\EShopDefault\Views\Shared\ControlTemplates\ControlType.Choice.cshtml" />
      <_ContentIncludedByDefault Remove="Themes\EShopDefault\Views\Shared\ControlTemplates\ControlType.RadioButtonPills.cshtml" />
      <_ContentIncludedByDefault Remove="Themes\EShopDefault\Views\Shared\ControlTemplates\ControlType.Swatch.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w1000.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w1001-crtrue.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w1001.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w922.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-main_logo-w9222.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000001-pexels-supliful-14029288-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000002-pexels-makrufinmuhammad-33538457-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000003-pexels-rubaitulazad-17220082-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000004-pexels-afterave-essentials-2011504051-29107590-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000005-pexels-karola-g-4735904-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000006-pexels-dogu-tuncer-339534179-16749129-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000006-pexels-dogu-tuncer-339534179-16749129-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000006-pexels-dogu-tuncer-339534179-16749129-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000006-pexels-dogu-tuncer-339534179-16749129-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000006-pexels-dogu-tuncer-339534179-16749129-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000007-pexels-shvetsa-5953781-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000007-pexels-shvetsa-5953781-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000007-pexels-shvetsa-5953781-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000007-pexels-shvetsa-5953781-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000007-pexels-shvetsa-5953781-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000008-pexels-sales-trust-162265874-10825665-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000009-pexels-haipham07-13549321-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000010-pexels-cup-of-couple-8015487-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000011-pexels-karola-g-5632335-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000012-pexels-deise-elen-2149983761-31406906-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000012-pexels-deise-elen-2149983761-31406906-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000012-pexels-deise-elen-2149983761-31406906-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000012-pexels-deise-elen-2149983761-31406906-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000012-pexels-deise-elen-2149983761-31406906-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000013-pexels-karola-g-4735905-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000014-pexels-ogutomacedo-13013761-w984.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000015-pexels-azka-nandya-91944639-9507137-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000016-pexels-roman-odintsov-7691161-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1141.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1323.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1535.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w1781.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w2066.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w2396.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w2780.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w3224.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w3740.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000017-pexels-cup-of-couple-8015482-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000018-pexels-alesiakozik-7796593-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000018-pexels-alesiakozik-7796593-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000018-pexels-alesiakozik-7796593-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000018-pexels-alesiakozik-7796593-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000018-pexels-alesiakozik-7796593-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000019-pexels-roman-odintsov-7691117-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000019-pexels-roman-odintsov-7691117-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000019-pexels-roman-odintsov-7691117-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000019-pexels-roman-odintsov-7691117-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000019-pexels-roman-odintsov-7691117-w3840.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000020-pexels-karola-g-4202325-w1152.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000020-pexels-karola-g-4202325-w1613.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000020-pexels-karola-g-4202325-w2259.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000020-pexels-karola-g-4202325-w3162.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\images\Cached\0000020-pexels-karola-g-4202325-w3840.jpg" />
    </ItemGroup>

</Project>
