<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>14</LangVersion>
</PropertyGroup>

<PropertyGroup>
    <OutputPath>..\EShop.Web\Modules\EShop.AzureBlobStorage</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    </ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\EShop.Core\EShop.Core.csproj"/>
    <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj"/>
    <ProjectReference Include="..\EShop.Web.Framework\EShop.Web.Framework.csproj"/>
</ItemGroup>

</Project>
