<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Content\Menus\" />
        <Folder Include="Data\Installation\Domain\" />
        <Folder Include="Platform\Identity\External\" />
        <Folder Include="Platform\Infructructure\" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
    </ItemGroup>

</Project>
