<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EShop.Core\EShop.Core.csproj" />
      <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
      <ProjectReference Include="..\EShop.Tests.Framework\EShop.Tests.Framework.csproj" />
    </ItemGroup>

</Project>
