<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EShop.Core\EShop.Core.csproj" />
      <ProjectReference Include="..\EShop.Tests.Framework\EShop.Tests.Framework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Themes\TestTheme\theme.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Themes\AnotherTestTheme\theme.config">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="ThemeTests\Files\Themes\AnotherTestTheme\theme.config" />
      <None Remove="ThemeTests\Files\Themes\TestTheme\theme.config" />
    </ItemGroup>

</Project>
